# Generated by Django 3.0 on 2019-12-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorerestaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantinfo',
            old_name='Address',
            new_name='address',
        ),
    ]
