# Generated by Django 2.2.6 on 2019-11-09 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesettings',
            name='profile_about',
        ),
        migrations.AddField(
            model_name='profileaboutitem',
            name='user_settings',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='profiles.ProfileSettings'),
            preserve_default=False,
        ),
    ]
