export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_DATA_START = "GET_DATA_START";
export const PROFILE_DATA_START = "PROFILE_DATA_START";
export const PROFILE_DATA_SUCCESS = "PROFILE_DATA_SUCCESS";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAIL = "GET_DATA_FAIL";
export const GET_DATA = "GET_DATA";
export const GET_RESTAURANTS_DATA = "GET_RESTAURANTS_DATA";
export const SET_IMAGE = "SET_IMAGE";

export const GET_IMAGE_DATA_START = "GET_IMAGE_DATA_START";
export const GET_IMAGE_DATA_SUCCESS = "GET_IMAGE_DATA_SUCCESS";
export const SET_IMAGE_START = "SET_IMAGE_START";
export const SET_IMAGE_SUCCESS = "SET_IMAGE_SUCCESS";

export const GET_FILTER_START = " GET_FILTER_START";
export const GET_FILTER_SUCCESS = "GET_FILTER_SUCCESS";
export const GET_FILTER_SETTING_START = "GET_FILTER_SETTING_START";
export const GET_FILTER_SETTING = "GET_FILTER_SETTING";
export const SET_FILTER_SUCCESS = "SET_FILTER_SUCCESS";
export const GET_FILTER_FAIL = "GET_FILTER_FAIL";

export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";

export const GET_LIST = "GET_LIST";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const GET_LIST_FAIL = "GET_LIST_FAIL";
export const GET_REQUEST_LIST_SUCCESS = "GET_REQUEST_LIST_SUCCESS";
export const REQUEST_START = "REQUEST_START";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAIL = "REQUEST_FAIL";
